### ISSUE TITLE
CSS Formatter plugin is not working and the right click format is not visible at all in SCSS file

### ISSUE THREAD

**Issue by marmeek** [aeschli/vscode-css-formatter#11]
- Extension Name: vscode-css-formatter
- Extension Version: 1.0.1
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by aeschli** [comment]
The formatter only works on CSS, not on SCSS, sorry.
