### ISSUE TITLE
After installing this extention, folders can not be renamed via Explorer in VS Code's Side Bar

### ISSUE THREAD

**Issue by Li-YangZhong** [aeschli/vscode-css-formatter#19]
After installing this extention, folders can not be renamed via Explorer in VS Code's Side Bar. After disabling this extention, problems disappear. VS Code version is 1.41.1

**Comment by elcste** [comment]
I can rename directories without issue using VS Core 1.43.2 (snap on Ubuntu 19.10).

**Comment by aeschli** [comment]
Not related to this extension. The extension provides a format provider and does not do any file operations by itself.
