### ISSUE TITLE
CSS formatter not working since VSCode 1.18 update

### ISSUE THREAD

**Issue by deventity** [aeschli/vscode-css-formatter#8]
Hi,

since the 1.18 update of VSCode, CSSFormatter is not working.
I always get this message 
![32691065-9a72eaaa-c702-11e7-912e-13078c2aece5](https://user-images.githubusercontent.com/33573453/32699411-84cbbbba-c7b5-11e7-8868-64a3e23ad55c.JPG)

**Comment by rzvjerkovic** [comment]
Same.

**Comment by deventity** [comment]
Wonder if there will be a fix, switched to Atom for now, because VSCode is not really usable without plugins like this.

FYI, other plugins do not work also.

Best Regards

**Comment by mrspaghetti** [comment]
Until this gets fixed it seems JS-CSS-HTML Formatter is still working

**Comment by aeschli** [comment]
Sorry for the late response. Fix is on the way

**Comment by deventity** [comment]
Awesome!
